# Generated by Django 3.1.4 on 2021-01-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='django.jpg', null=True, upload_to='images/'),
        ),
    ]
